### PR TITLE
(outdated) Low-level protocol JSON schema

### PR DESCRIPTION
**Pull request by pierluca**
The $id for now is a bit meaningless, but this should provide a basis to move forward.

Protocol specifications : https://docs.google.com/document/d/1fyNWSPzLhM6W9V0VTFf2waMLiJGcscy7wa4bQlLkySM/edit?ts=5fa967b8#

JSON Schema reference : https://json-schema.org

### CODE REVIEW

**Comment by pierluca** [comment]
The following should be added to most JSONs, for strictness `"additionalProperties": false`

**Comment by SFulpius** [comment]
The schemas looks good overall.
However, I think the schema used by the server to send to clients published messages is missing.

**Comment by pierluca** [comment]
@SFulpius This is the low-level communication across the websocket connection, as such the "message" can be sent from either client or server to the other.

**Comment by SFulpius** [comment]
@pierluca So the action would be "message"? And what should we do with the req_id field, as it is not a request from the client? Should we omit it?

**Comment by SFulpius** [comment]
Closing because we have a new PR for the protocol.

**Pull request closed without merging**
