### PR TITLE
be2: Verify signature and compute ID

### LINKED ISSUE #53: Verify digital signature on messages

### PR DESCRIPTION
**Pull request by SFulpius**
Verify the signature on a message and compute the message ID.
Closes #53 and #59.

### CODE REVIEW

**Review by RaulinN — CHANGES_REQUESTED** [review]
Nice! I have a question and a suggestion for you! 

- Question: What is the format you expect as input for `Hex` values (keys (organizer and witnesses), hashes and signatures). I see you are manually adding the `0x` prefix in front of the `Hex` value (`Hash.scala:18`) to conform to the JsonProtocol. In the parser I am writing, I parse `Hex` values by removing the `0x` and then transforming the resulting `String` into an `Int` value. Do you prefer something else?

- Suggestion: add the Scorex dependency in `readme.md`

**Comment by SFulpius** [comment]
@RaulinN On `Hash.scala:18`, the "%02x" string is used to format binary data in hexadecimal, but it does not add 0x before it.
Also, you should not transform an hexadecimal into an Int. Public keys and signature are 256 bits long, thus it won't fit in a 32 bits Int.
In the parser, just removing the 0x should work with the code I wrote.

**Comment by SFulpius** [comment]
@RaulinN I updated the README.

**Review by lhmerino — APPROVED** [review]
Looks great!

**Review by RaulinN — APPROVED** [review]

**Pull request merged**
